apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: storage-provider-runtime-config
spec:
  deploymentTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: storage-provider-runtime-config
      annotations:
        iam.gke.io/gcp-service-account: cp-unprivileged@<project>.iam.gserviceaccount.com
    spec:
      selector:
        matchLabels:
          pkg.crossplane.io/provider: provider-gcp-storage
      template:
        metadata:
          labels:
            pkg.crossplane.io/provider: provider-gcp-storage
          annotations: 
            iam.gke.io/gcp-service-account: cp-unprivileged@<project>.iam.gserviceaccount.com
        spec:
          containers:
          - name: package-runtime
  serviceAccountTemplate:
    metadata:
      name: provider-gcp-storage
      annotations: 
        iam.gke.io/gcp-service-account: cp-unprivileged@<project>.iam.gserviceaccount.com