apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: storage-provider-config
spec:
  credentials:
    source: ImpersonateServiceAccount
    impersonateServiceAccount:
      name: cp-storage@<project>.iam.gserviceaccount.com
  projectID: <project>