apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: storage-provider-config
spec:
  credentials:
    source: ImpersonateServiceAccount
    impersonateServiceAccount:
      name: crossplane-svc@mike-berry-sandbox.iam.gserviceaccount.com
  projectID: mike-berry-sandbox